# Generated by Django 2.2.6 on 2020-01-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('IdentityS', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
