# Generated by Django 2.2.6 on 2020-01-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200107_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENTs',
            fields=[
                ('Years', models.IntegerField()),
                ('IdentityS', models.AutoField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='STUDENT',
        ),
    ]
