# Generated by Django 2.2.6 on 2020-01-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200107_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='IdentityS',
            new_name='identityS',
        ),
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.TextField(default='unNamed', max_length=200),
        ),
    ]
