# Generated by Django 2.2.6 on 2020-01-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200107_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'STUDENT', 'verbose_name_plural': 'List students'},
        ),
    ]
