# Generated by Django 2.2.6 on 2020-01-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200107_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'STUDENT', 'verbose_name_plural': 'Học Sinh'},
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.TextField(default='unNamed', max_length=200, verbose_name='Ho ten:'),
        ),
    ]
