# Generated by Django 2.2.6 on 2020-01-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20200107_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Years',
            field=models.IntegerField(default=2019, verbose_name='Năm vào học'),
        ),
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateField(verbose_name='Ảnh thẻ'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], default='M', max_length=2, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='students',
            name='identityS',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã HS'),
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Ảnh thẻ'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Họ và tên'),
        ),
    ]
