# Generated by Django 2.2.6 on 2020-01-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200107_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STUDENTs',
            new_name='STUDENT',
        ),
    ]
