# Generated by Django 2.2.6 on 2020-01-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200107_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identityS',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã HS'),
        ),
    ]
