# Generated by Django 2.2.6 on 2020-01-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20200111_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phonenumdad',
            field=models.CharField(max_length=20, null=True, verbose_name='SĐT bố'),
        ),
        migrations.AddField(
            model_name='student',
            name='phonenummom',
            field=models.CharField(max_length=20, null=True, verbose_name='SĐT mẹ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dobdad',
            field=models.IntegerField(null=True, verbose_name='Năm sinh bố'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dobmom',
            field=models.IntegerField(null=True, verbose_name='Năm sinh bố'),
        ),
    ]
