# Generated by Django 2.2.6 on 2020-01-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20200111_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('identityT', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã GV')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Họ và tên')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], default='M', max_length=2, verbose_name='Giới tính')),
                ('dob', models.DateField(verbose_name='Ngày sinh')),
                ('hometown', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quê quán')),
                ('ethnic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dân tộc')),
                ('religion', models.CharField(blank=True, default='Không', max_length=100, null=True, verbose_name='Tôn giáo')),
                ('datebegin', models.DateField(blank=True, null=True, verbose_name='Ngày vào dạy')),
                ('addr', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Địa chỉ thường trú')),
                ('phonenum', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại liên hệ')),
                ('status', models.CharField(choices=[('ON', 'Đang dạy'), ('OFF', 'Thôi dạy')], default='ON', max_length=5, verbose_name='Trạng thái')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='', verbose_name='Ảnh thẻ')),
                ('edit', models.ImageField(blank=True, default='edit.png', null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='Years',
            field=models.IntegerField(default=2019, verbose_name='Khóa học (VD:2019) '),
        ),
        migrations.AlterField(
            model_name='student',
            name='addr',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Địa chỉ thường trú'),
        ),
        migrations.AlterField(
            model_name='student',
            name='datebegin',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày nhập học'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dobdad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm sinh bố'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dobmom',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm sinh bố'),
        ),
        migrations.AlterField(
            model_name='student',
            name='edit',
            field=models.ImageField(blank=True, default='edit.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='ethnic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dân tộc'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hometown',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quê quán'),
        ),
        migrations.AlterField(
            model_name='student',
            name='jobdad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nghề nghiệp bố'),
        ),
        migrations.AlterField(
            model_name='student',
            name='jobmom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nghề nghiệp mẹ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='namedad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Họ tên bố'),
        ),
        migrations.AlterField(
            model_name='student',
            name='namemom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Họ tên mẹ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại liên hệ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenumdad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT bố'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenummom',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT mẹ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, default='Không', max_length=100, null=True, verbose_name='Tôn giáo'),
        ),
    ]
