# Generated by Django 2.2.6 on 2020-01-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_teacher_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('identityC', models.CharField(help_text='VD: 2019A, 2018B', max_length=10, primary_key=True, serialize=False, verbose_name='Mã Lớp học')),
                ('classname', models.CharField(help_text='VD: 1A, 2B', max_length=10, verbose_name='Tên Lớp học')),
                ('gvcn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Teacher')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
            },
        ),
    ]
