# Generated by Django 2.2.6 on 2020-01-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='edit',
            field=models.ImageField(blank=True, default='edit.png', null=True, upload_to=''),
        ),
    ]
