# Generated by Django 2.2.6 on 2020-01-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_class_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='', verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='', verbose_name='Ảnh'),
        ),
    ]
