# Generated by Django 2.2.6 on 2020-01-13 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleWeek',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('note', models.CharField(help_text='VD: Lớp trực tuần, ...', max_length=500, verbose_name='Ghi chú')),
                ('caption', models.TextField(blank=True, help_text='VD: Nhắc nhở, Thông tin thêm...', verbose_name='Nội dung')),
                ('image', models.ImageField(help_text='VD: Lịch công tác', null=True, upload_to='', verbose_name='Hình ảnh')),
                ('submission_date', models.DateTimeField(default=datetime.datetime(2020, 1, 13, 14, 43, 30, 978969), editable=False)),
            ],
            options={
                'verbose_name': 'Lịch công tác',
                'verbose_name_plural': 'Lịch công tác',
            },
        ),
    ]
