# Generated by Django 2.2.6 on 2020-01-13 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleweek',
            name='thumb',
            field=models.ImageField(help_text='Hiển thị trên trang chủ', null=True, upload_to='', verbose_name='Thumb'),
        ),
        migrations.AlterField(
            model_name='scheduleweek',
            name='image',
            field=models.ImageField(help_text='Lịch công tác', null=True, upload_to='', verbose_name='Lịch công tác'),
        ),
        migrations.AlterField(
            model_name='scheduleweek',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 14, 49, 43, 934774), editable=False),
        ),
    ]
