# Generated by Django 2.2.6 on 2020-01-13 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200113_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 5, 32, 37836), editable=False),
        ),
        migrations.AlterField(
            model_name='scheduleweek',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 5, 32, 36992), editable=False),
        ),
    ]
