# Generated by Django 2.2.6 on 2020-01-13 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20200113_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 31, 18, 849654), editable=False),
        ),
        migrations.AlterField(
            model_name='scheduleweek',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 31, 18, 848867), editable=False),
        ),
    ]
