# Generated by Django 2.2.6 on 2020-01-13 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20200113_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('note', models.CharField(help_text='VD: Văn bản số, quyết định ...', max_length=500, verbose_name='Ghi chú')),
                ('caption', models.TextField(blank=True, verbose_name='Nội dung')),
                ('thumb', models.ImageField(help_text='Hiển thị trên trang chủ', null=True, upload_to='', verbose_name='Thumb')),
                ('file', models.FileField(blank=True, help_text='Văn bản', null=True, upload_to='', verbose_name='File đính kèm')),
                ('submission_date', models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 52, 16, 505385), editable=False)),
                ('edit', models.ImageField(blank=True, default='edit.png', null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Văn bản trường',
                'verbose_name_plural': 'Văn bản trường',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('note', models.CharField(help_text='VD: Lớp trực tuần, ...', max_length=500, verbose_name='Ghi chú')),
                ('caption', models.TextField(blank=True, help_text='VD: Nhắc nhở, Thông tin thêm...', verbose_name='Nội dung')),
                ('thumb', models.ImageField(help_text='Hiển thị trên trang chủ', null=True, upload_to='', verbose_name='Thumb')),
                ('image', models.ImageField(help_text='Thông tin, hình ảnh', null=True, upload_to='', verbose_name='Hình ảnh')),
                ('submission_date', models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 52, 16, 504508), editable=False)),
                ('edit', models.ImageField(blank=True, default='edit.png', null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Tin tức, Sự kiện',
                'verbose_name_plural': 'Tin tức, Sự kiện',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 52, 16, 503857), editable=False),
        ),
        migrations.AlterField(
            model_name='scheduleweek',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 52, 16, 503072), editable=False),
        ),
    ]
