# Generated by Django 2.2.6 on 2020-01-13 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20200113_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Văn bản', null=True, upload_to='', verbose_name='File đính kèm'),
        ),
        migrations.AlterField(
            model_name='document',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 19, 25, 44, 367954), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 19, 25, 44, 367132), editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 19, 25, 44, 366509), editable=False),
        ),
        migrations.AlterField(
            model_name='scheduleweek',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 19, 25, 44, 365804), editable=False),
        ),
    ]
